#!/bin/sh
set -e

# Install the necessary files for bluetooth reading
sudo apt-get update
sudo apt-get -y install bluez

# Create our directories
sudo mkdir /var/log/bluedump /opt/bluedump
sudo chown $USER /var/log/bluedump /opt/bluedump

# Install Bluedump as a service
curl -L https://github.com/mal-virus/bluedump/raw/master/bluedump.tar.gz -o /tmp/bluedump.tar.gz
sudo tar -xzf /tmp/bluedump.tar.gz -C /opt/bluedump
sudo chmod +x /opt/bluedump/*
sudo mv /opt/bluedump/bluedump /etc/init.d/bluedump
sudo chown root /etc/init.d/bluedump
sudo update-rc.d bluedump defaults
rm /tmp/bluedump.tar.gz

# Inform user
echo "
BlueDump installed as a service
Restart Machine to complete"
